site_name: IMS322 Docs
theme:
  name: material
  palette:
    - media: '(prefers-color-scheme)'
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
nav:
  - Home: index.md
  - Setup: setup.md
  - Coding Style & Requirements: style-requirements.md
  - HTML:
      - Introduction: html/introduction.md
      - Attributes: html/attributes.md
      - Elements: html/elements.md
      - Semantic HTML: html/semantic-html.md
  - CSS:
      - Introduction: css/introduction.md
      - Box Model: css/box-model.md
      - Flexbox: css/flexbox.md
      - Grid: css/grid.md
      - Hover: css/hover.md
      - Input Styling: css/input-styling.md
      - Mobile-First Design: css/mobile-first.md
      - Nesting: css/nesting.md
      - Properties and Units: css/properties-units.md
      - RWD Overview: css/rwd-overview.md
      - Transitions: css/transitions.md
      - Typography: css/typography.md
      - Variables: css/variables.md
  - JavaScript:
      - Introduction: js/introduction.md
      - Arrays: js/arrays.md
      - Class Toggling: js/class-toggling.md
      - Conditionals: js/conditionals.md
      - Data Types: js/data-types.md
      - DOM Manipulation: js/dom-manipulation.md
      - DOM Properties and Methods: js/dom-properties-and-methods.md
      - Event Listeners: js/event-listeners.md
      - For Loops: js/for-loops.md
      - Forms: js/forms.md
      - Functions: js/functions.md
      - Manipulating Style Properties: js/manipulating-style-properties.md
      - Modals: js/modals.md
      - More Functions: js/more-functions.md
      - More Input Types: js/more-input-types.md
      - Objects: js/objects.md
      - Operators: js/operators.md
      - Using the Console: js/using-the-console.md
      - Variables: js/variables.md
  - Resources:
      - Introduction: res/introduction.md
      - Additional Resources: res/additional-resources.md
      - Artificial Intelligence: res/ai.md
      - Browser Review: res/browser-review.md
      - Optimizing Images: res/optimizing-images.md
      - Utilities: res/utilities.md
